version: "3.9"

volumes:
  db_data:

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=url_shortcuter
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data=/var/lib/postgresql/data
    restart: always

  url_shortcut:
    container_name: url_shortcut
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_shortcuter
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db

